/*
  Catálogo da Karma Games.

  Para adicionar um jogo:
    1. Crie a pasta  jogos/<slug>/  com um index.html dentro (o jogo).
    2. Coloque uma imagem de capa em  assets/capas/<slug>.webp  (16:10, ~800x500).
    3. Copie um bloco abaixo e preencha os campos.

  Campos:
    slug       identificador curto, sem espaços (vira o endereço: jogar.html?j=slug)
    titulo     nome que aparece no site
    descricao  uma frase curta
    categoria  "Arcade" | "Quebra-cabeça" | "Clássicos" | "Ação" | ... (cria filtro sozinho)
    controles  texto curto mostrado na página do jogo
    autor      quem fez
    autoral    opcional: true para jogos feitos por você. Eles aparecem na seção "Feitos aqui"
    url        opcional: link de jogo hospedado fora (abre no iframe). Sem url, usa jogos/<slug>/
    destaque   opcional: true coloca o jogo no topo da página inicial
    emBreve    opcional: true mostra o jogo na seção "Em breve", sem botão de jogar
    adicionado data no formato AAAA-MM-DD (jogos dos últimos 30 dias ganham selo "Novo")
*/
window.KARMA_JOGOS = [
  {
    slug: "behind-the-grid",
    capa: "assets/capas/behind-the-grid.svg",
    titulo: "Behind The Grid",
    descricao: "Crie seu perfil, poste, feche publis e sobreviva ao hate. O feed é perfeito; os bastidores, nem tanto.",
    categoria: "Simulação",
    controles: "Clique ou toque nas ações · deslize o card para ver os bastidores",
    autor: "Karma Games",
    autoral: true,
    destaque: true,
    adicionado: "2026-10-08",
  },
  {
    slug: "paciencia",
    capa: "assets/capas/paciencia.svg",
    titulo: "Paciência",
    descricao: "O clássico das cartas: organize os naipes do Ás ao Rei. Vira 1 ou 3 cartas.",
    categoria: "Clássicos",
    controles: "Arraste as cartas · toque para selecionar · dois cliques manda pra fundação",
    autor: "Karma Games",
    adicionado: "2026-10-08",
  },
  {
    slug: "blocos",
    capa: "assets/capas/blocos.svg",
    titulo: "Blocos Caindo",
    descricao: "Encaixe as peças que caem e limpe linhas antes que a pilha chegue ao topo.",
    categoria: "Arcade",
    controles: "Setas movem · ↑ gira · Espaço derruba · C guarda · no celular: botões e gestos",
    autor: "Karma Games",
    adicionado: "2026-10-08",
  },
  {
    slug: "sudoku",
    capa: "assets/capas/sudoku.svg",
    titulo: "Sudoku",
    descricao: "Complete a grade 9x9 sem repetir números. Puzzles novos toda vez, com anotações e dicas.",
    categoria: "Quebra-cabeça",
    controles: "Toque na casa e no número · setas e teclas 1 a 9 · N anota",
    autor: "Karma Games",
    adicionado: "2026-10-08",
  },
  {
    slug: "forca",
    capa: "assets/capas/forca.svg",
    titulo: "Forca",
    descricao: "Adivinhe a palavra letra por letra antes que o bonequinho fique completo.",
    categoria: "Clássicos",
    controles: "Clique nas letras ou use o teclado",
    autor: "Karma Games",
    adicionado: "2026-10-08",
  },
  {
    slug: "xadrez",
    capa: "assets/capas/xadrez.svg",
    titulo: "Xadrez",
    descricao: "O clássico dos reis: dê xeque-mate no computador ou desafie um amigo.",
    categoria: "Tabuleiro",
    controles: "Clique na peça e depois na casa · ou arraste",
    autor: "Karma Games",
    destaque: true,
    adicionado: "2026-10-08",
  },
  {
    slug: "dama",
    capa: "assets/capas/dama.svg",
    titulo: "Dama",
    descricao: "Damas na regra brasileira: captura obrigatória, lei da maioria e dama voadora.",
    categoria: "Tabuleiro",
    controles: "Clique na peça e depois na casa de destino",
    autor: "Karma Games",
    adicionado: "2026-10-08",
  },
  {
    slug: "ligue-4",
    capa: "assets/capas/ligue-4.svg",
    titulo: "Ligue 4",
    descricao: "Solte as fichas e alinhe quatro antes do adversário.",
    categoria: "Tabuleiro",
    controles: "Clique na coluna · setas e Enter · teclas 1 a 7",
    autor: "Karma Games",
    adicionado: "2026-10-08",
  },
  {
    slug: "reversi",
    capa: "assets/capas/reversi.svg",
    titulo: "Reversi",
    descricao: "Cerque as peças do adversário e vire o tabuleiro pra sua cor.",
    categoria: "Tabuleiro",
    controles: "Clique ou toque numa casa marcada",
    autor: "Karma Games",
    adicionado: "2026-10-08",
  },
  {
    slug: "pedra-papel-tesoura",
    titulo: "Pedra, Papel e Tesoura",
    descricao: "Jo, ken, pô! Mãos bochechudas disputam melhor de 5 contra o computador.",
    categoria: "Clássicos",
    controles: "Teclas 1, 2 e 3 · clique ou toque nos botões",
    autor: "Karma Games",
    capa: "assets/capas/pedra-papel-tesoura.svg",
    adicionado: "2026-10-04",
  },
  {
    slug: "biscoito",
    titulo: "Biscoito Gigante",
    descricao: "Clique no biscoitão, contrate vovós e encha o mundo de biscoito.",
    categoria: "Casual",
    controles: "Clique ou Espaço no biscoito · 1 a 6 compram melhorias",
    autor: "Karma Games",
    capa: "assets/capas/biscoito.svg",
    adicionado: "2026-10-04",
  },
  {
    slug: "genius",
    titulo: "Genius",
    descricao: "Olhe, escute e repita a sequência de cores que não para de crescer.",
    categoria: "Clássicos",
    controles: "Q W A S ou setas · clique ou toque nas cores",
    autor: "Karma Games",
    capa: "assets/capas/genius.svg",
    adicionado: "2026-10-04",
  },
  {
    slug: "torre",
    titulo: "Torre de Blocos",
    descricao: "Empilhe blocos fofinhos até o céu, e capriche no acerto perfeito!",
    categoria: "Arcade",
    controles: "Espaço, clique ou toque para soltar o bloco",
    autor: "Karma Games",
    capa: "assets/capas/torre.svg",
    adicionado: "2026-10-04",
  },
  {
    slug: "pescaria",
    titulo: "Pescaria",
    descricao: "Ajude o gatinho a pescar o máximo em 60 segundos, sem fisgar bota velha!",
    categoria: "Casual",
    controles: "Segure Espaço, o mouse ou o dedo para descer o anzol; setas movem o barco",
    autor: "Karma Games",
    capa: "assets/capas/pescaria.svg",
    adicionado: "2026-10-04",
  },
  {
    slug: "meteoros",
    titulo: "Desvia dos Meteoros",
    descricao: "Pilote a navezinha, fuja das pedras bravas e junte estrelas!",
    categoria: "Ação",
    controles: "Setas ou A/D, mouse ou arrastar o dedo",
    autor: "Karma Games",
    capa: "assets/capas/meteoros.svg",
    adicionado: "2026-10-04",
  },
  {
    slug: "toupeira",
    titulo: "Acerta a Toupeira",
    descricao: "30 segundos pra martelar toda toupeira que botar a cara pra fora. Só não vale acertar a bomba!",
    categoria: "Arcade",
    controles: "Clique ou toque nas toupeiras · teclas 1 a 9 · P pausa · M som",
    autor: "Karma Games",
    capa: "assets/capas/toupeira.svg",
    adicionado: "2026-10-04",
  },
  {
    slug: "balao",
    titulo: "Estoura Balão",
    descricao: "Estoure os balões fofinhos antes que eles fujam pro céu. Os dourados valem 5!",
    categoria: "Casual",
    controles: "Clique ou toque nos balões · setas e Espaço para mirar · P pausa · M som",
    autor: "Karma Games",
    capa: "assets/capas/balao.svg",
    adicionado: "2026-10-04",
  },
  {
    slug: "galinha",
    titulo: "Corre Galinha",
    descricao: "Uma galinha em fuga pela fazenda: pule cercas e baldes e veja até onde ela chega.",
    categoria: "Arcade",
    controles: "Espaço, seta para cima, clique ou toque para pular (segure para ir mais alto) · P pausa · M som",
    autor: "Karma Games",
    capa: "assets/capas/galinha.svg",
    adicionado: "2026-10-04",
  },

  {
    slug: "voo-livre",
    capa: "assets/capas/voo-livre.svg",
    titulo: "Voo Livre",
    descricao: "Bata as asas, passe entre as colunas e não encoste em nada.",
    categoria: "Arcade",
    controles: "Espaço, clique ou toque para voar",
    autor: "Karma Games",
    destaque: true,
    adicionado: "2026-10-03",
  },
  {
    slug: "cobrinha",
    capa: "assets/capas/cobrinha.svg",
    titulo: "Cobrinha",
    descricao: "Coma, cresça e não morda o próprio rabo.",
    categoria: "Clássicos",
    controles: "Setas ou WASD · deslize no celular",
    autor: "Karma Games",
    adicionado: "2026-10-03",
  },
  {
    slug: "2048",
    capa: "assets/capas/2048.svg",
    titulo: "2048",
    descricao: "Junte números iguais até chegar no 2048.",
    categoria: "Quebra-cabeça",
    controles: "Setas ou WASD · deslize no celular",
    autor: "Karma Games",
    adicionado: "2026-10-03",
  },
  {
    slug: "quebra-blocos",
    capa: "assets/capas/quebra-blocos.svg",
    titulo: "Quebra-Blocos",
    descricao: "Rebata a bola e derrube todos os blocos da fase.",
    categoria: "Arcade",
    controles: "Mouse, setas ou arraste o dedo",
    autor: "Karma Games",
    adicionado: "2026-10-03",
  },
  {
    slug: "campo-minado",
    capa: "assets/capas/campo-minado.svg",
    titulo: "Campo Minado",
    descricao: "Abra o campo inteiro sem pisar em nenhuma mina.",
    categoria: "Quebra-cabeça",
    controles: "Clique para abrir · botão direito ou toque longo marca",
    autor: "Karma Games",
    adicionado: "2026-10-03",
  },
  {
    slug: "memoria",
    capa: "assets/capas/memoria.svg",
    titulo: "Jogo da Memória",
    descricao: "Vire as cartas e encontre todos os pares no menor número de jogadas.",
    categoria: "Quebra-cabeça",
    controles: "Clique ou toque nas cartas",
    autor: "Karma Games",
    adicionado: "2026-10-03",
  },
  {
    slug: "pong",
    capa: "assets/capas/pong.svg",
    titulo: "Pong",
    descricao: "O primeiro jogo de bola contra o computador. Faça 7 pontos.",
    categoria: "Clássicos",
    controles: "Mouse, setas ou arraste o dedo",
    autor: "Karma Games",
    adicionado: "2026-10-03",
  },
  {
    slug: "jogo-da-velha",
    capa: "assets/capas/jogo-da-velha.svg",
    titulo: "Jogo da Velha",
    descricao: "Contra o computador ou contra um amigo no mesmo aparelho.",
    categoria: "Clássicos",
    controles: "Clique ou toque na casa",
    autor: "Karma Games",
    adicionado: "2026-10-03",
  },
];
